// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'data_search.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DataSearch _$DataSearchFromJson(Map<String, dynamic> json) => DataSearch(
      totalCount: (json['totalCount'] as num?)?.toDouble(),
      incompleteResults: json['incompleteResults'] as bool?,
      items: (json['items'] as List<dynamic>?)
          ?.map((e) => Items.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$DataSearchToJson(DataSearch instance) =>
    <String, dynamic>{
      'totalCount': instance.totalCount,
      'incompleteResults': instance.incompleteResults,
      'items': instance.items?.map((e) => e.toJson()).toList(),
    };

Items _$ItemsFromJson(Map<String, dynamic> json) => Items(
      id: (json['id'] as num?)?.toDouble(),
      nodeId: json['nodeId'] as String?,
      name: json['name'] as String?,
      fullName: json['full_name'] as String?,
      private: json['private'] as bool?,
      owner: json['owner'] == null
          ? null
          : Owner.fromJson(json['owner'] as Map<String, dynamic>),
      htmlUrl: json['htmlUrl'] as String?,
      description: json['description'] as String?,
      fork: json['fork'] as bool?,
      url: json['url'] as String?,
      forksUrl: json['forksUrl'] as String?,
      keysUrl: json['keysUrl'] as String?,
      collaboratorsUrl: json['collaboratorsUrl'] as String?,
      teamsUrl: json['teamsUrl'] as String?,
      hooksUrl: json['hooksUrl'] as String?,
      issueEventsUrl: json['issueEventsUrl'] as String?,
      eventsUrl: json['eventsUrl'] as String?,
      assigneesUrl: json['assigneesUrl'] as String?,
      branchesUrl: json['branchesUrl'] as String?,
      tagsUrl: json['tagsUrl'] as String?,
      blobsUrl: json['blobsUrl'] as String?,
      gitTagsUrl: json['gitTagsUrl'] as String?,
      gitRefsUrl: json['gitRefsUrl'] as String?,
      treesUrl: json['treesUrl'] as String?,
      statusesUrl: json['statusesUrl'] as String?,
      languagesUrl: json['languages_url'] as String?,
      stargazersUrl: json['stargazersUrl'] as String?,
      contributorsUrl: json['contributorsUrl'] as String?,
      subscribersUrl: json['subscribersUrl'] as String?,
      subscriptionUrl: json['subscriptionUrl'] as String?,
      commitsUrl: json['commitsUrl'] as String?,
      gitCommitsUrl: json['gitCommitsUrl'] as String?,
      commentsUrl: json['commentsUrl'] as String?,
      issueCommentUrl: json['issueCommentUrl'] as String?,
      contentsUrl: json['contentsUrl'] as String?,
      compareUrl: json['compareUrl'] as String?,
      mergesUrl: json['mergesUrl'] as String?,
      archiveUrl: json['archiveUrl'] as String?,
      downloadsUrl: json['downloadsUrl'] as String?,
      issuesUrl: json['issuesUrl'] as String?,
      pullsUrl: json['pullsUrl'] as String?,
      milestonesUrl: json['milestonesUrl'] as String?,
      notificationsUrl: json['notificationsUrl'] as String?,
      labelsUrl: json['labelsUrl'] as String?,
      releasesUrl: json['releasesUrl'] as String?,
      deploymentsUrl: json['deploymentsUrl'] as String?,
      createdAt: json['createdAt'] as String?,
      updatedAt: json['updatedAt'] as String?,
      pushedAt: json['pushedAt'] as String?,
      gitUrl: json['gitUrl'] as String?,
      sshUrl: json['sshUrl'] as String?,
      cloneUrl: json['cloneUrl'] as String?,
      svnUrl: json['svnUrl'] as String?,
      homepage: json['homepage'] as String?,
      size: (json['size'] as num?)?.toDouble(),
      stargazersCount: (json['stargazers_count'] as num?)?.toDouble(),
      watchersCount: (json['watchersCount'] as num?)?.toDouble(),
      language: json['language'] as String?,
      hasIssues: json['hasIssues'] as bool?,
      hasProjects: json['hasProjects'] as bool?,
      hasDownloads: json['hasDownloads'] as bool?,
      hasWiki: json['hasWiki'] as bool?,
      hasPages: json['hasPages'] as bool?,
      forksCount: (json['forksCount'] as num?)?.toDouble(),
      archived: json['archived'] as bool?,
      disabled: json['disabled'] as bool?,
      openIssuesCount: (json['openIssuesCount'] as num?)?.toDouble(),
      allowForking: json['allowForking'] as bool?,
      isTemplate: json['isTemplate'] as bool?,
      topics:
          (json['topics'] as List<dynamic>?)?.map((e) => e as String).toList(),
      visibility: json['visibility'] as String?,
      forks: (json['forks'] as num?)?.toDouble(),
      openIssues: (json['open_issues'] as num?)?.toDouble(),
      watchers: (json['watchers'] as num?)?.toDouble(),
      defaultBranch: json['defaultBranch'] as String?,
      score: (json['score'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$ItemsToJson(Items instance) => <String, dynamic>{
      'id': instance.id,
      'nodeId': instance.nodeId,
      'name': instance.name,
      'full_name': instance.fullName,
      'private': instance.private,
      'owner': instance.owner?.toJson(),
      'htmlUrl': instance.htmlUrl,
      'description': instance.description,
      'fork': instance.fork,
      'url': instance.url,
      'forksUrl': instance.forksUrl,
      'keysUrl': instance.keysUrl,
      'collaboratorsUrl': instance.collaboratorsUrl,
      'teamsUrl': instance.teamsUrl,
      'hooksUrl': instance.hooksUrl,
      'issueEventsUrl': instance.issueEventsUrl,
      'eventsUrl': instance.eventsUrl,
      'assigneesUrl': instance.assigneesUrl,
      'branchesUrl': instance.branchesUrl,
      'tagsUrl': instance.tagsUrl,
      'blobsUrl': instance.blobsUrl,
      'gitTagsUrl': instance.gitTagsUrl,
      'gitRefsUrl': instance.gitRefsUrl,
      'treesUrl': instance.treesUrl,
      'statusesUrl': instance.statusesUrl,
      'languages_url': instance.languagesUrl,
      'stargazersUrl': instance.stargazersUrl,
      'contributorsUrl': instance.contributorsUrl,
      'subscribersUrl': instance.subscribersUrl,
      'subscriptionUrl': instance.subscriptionUrl,
      'commitsUrl': instance.commitsUrl,
      'gitCommitsUrl': instance.gitCommitsUrl,
      'commentsUrl': instance.commentsUrl,
      'issueCommentUrl': instance.issueCommentUrl,
      'contentsUrl': instance.contentsUrl,
      'compareUrl': instance.compareUrl,
      'mergesUrl': instance.mergesUrl,
      'archiveUrl': instance.archiveUrl,
      'downloadsUrl': instance.downloadsUrl,
      'issuesUrl': instance.issuesUrl,
      'pullsUrl': instance.pullsUrl,
      'milestonesUrl': instance.milestonesUrl,
      'notificationsUrl': instance.notificationsUrl,
      'labelsUrl': instance.labelsUrl,
      'releasesUrl': instance.releasesUrl,
      'deploymentsUrl': instance.deploymentsUrl,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'pushedAt': instance.pushedAt,
      'gitUrl': instance.gitUrl,
      'sshUrl': instance.sshUrl,
      'cloneUrl': instance.cloneUrl,
      'svnUrl': instance.svnUrl,
      'homepage': instance.homepage,
      'size': instance.size,
      'stargazers_count': instance.stargazersCount,
      'watchersCount': instance.watchersCount,
      'language': instance.language,
      'hasIssues': instance.hasIssues,
      'hasProjects': instance.hasProjects,
      'hasDownloads': instance.hasDownloads,
      'hasWiki': instance.hasWiki,
      'hasPages': instance.hasPages,
      'forksCount': instance.forksCount,
      'archived': instance.archived,
      'disabled': instance.disabled,
      'openIssuesCount': instance.openIssuesCount,
      'allowForking': instance.allowForking,
      'isTemplate': instance.isTemplate,
      'topics': instance.topics,
      'visibility': instance.visibility,
      'forks': instance.forks,
      'open_issues': instance.openIssues,
      'watchers': instance.watchers,
      'defaultBranch': instance.defaultBranch,
      'score': instance.score,
    };

Owner _$OwnerFromJson(Map<String, dynamic> json) => Owner(
      login: json['login'] as String?,
      id: (json['id'] as num?)?.toDouble(),
      nodeId: json['nodeId'] as String?,
      avatarUrl: json['avatar_url'] as String?,
      gravatarId: json['gravatarId'] as String?,
      url: json['url'] as String?,
      htmlUrl: json['htmlUrl'] as String?,
      followersUrl: json['followersUrl'] as String?,
      followingUrl: json['followingUrl'] as String?,
      gistsUrl: json['gistsUrl'] as String?,
      starredUrl: json['starredUrl'] as String?,
      subscriptionsUrl: json['subscriptionsUrl'] as String?,
      organizationsUrl: json['organizationsUrl'] as String?,
      reposUrl: json['reposUrl'] as String?,
      eventsUrl: json['eventsUrl'] as String?,
      receivedEventsUrl: json['receivedEventsUrl'] as String?,
      type: json['type'] as String?,
      siteAdmin: json['siteAdmin'] as bool?,
    );

Map<String, dynamic> _$OwnerToJson(Owner instance) => <String, dynamic>{
      'login': instance.login,
      'id': instance.id,
      'nodeId': instance.nodeId,
      'avatar_url': instance.avatarUrl,
      'gravatarId': instance.gravatarId,
      'url': instance.url,
      'htmlUrl': instance.htmlUrl,
      'followersUrl': instance.followersUrl,
      'followingUrl': instance.followingUrl,
      'gistsUrl': instance.gistsUrl,
      'starredUrl': instance.starredUrl,
      'subscriptionsUrl': instance.subscriptionsUrl,
      'organizationsUrl': instance.organizationsUrl,
      'reposUrl': instance.reposUrl,
      'eventsUrl': instance.eventsUrl,
      'receivedEventsUrl': instance.receivedEventsUrl,
      'type': instance.type,
      'siteAdmin': instance.siteAdmin,
    };
